# Generated by Django 4.2.7 on 2024-01-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Science-Fiction', 'Science-Fiction'), ('Memoir', 'Memoir'), ('Self-Help', 'Self-Help'), ('Health', 'Health'), ('Travel', 'Travel'), ('History', 'History'), ('Poetry', 'Poetry'), ('Cooking', 'Cooking'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Art', 'Art'), ('Philosophy', 'Philosophy'), ('Science', 'Science'), ('Technology', 'Technology')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/media/uploads')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('borrowers', models.ManyToManyField(blank=True, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
